# File Options
files:
  include: 'src/main/webapp/resources/sass/**/*.s+(a|c)ss'
  ignore:
    - 'src/main/webapp/resources/sass/mixins/*.s+(a|c)ss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  nesting-depth:
    - 0
